# Generated by Django 3.1.4 on 2021-01-13 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='At_Risk',
            fields=[
                ('phno', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('age', models.IntegerField(null=True)),
                ('symptom', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=100)),
                ('travel', models.CharField(max_length=100)),
                ('apply', models.CharField(max_length=100)),
                ('result', models.CharField(default='low', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('total_cases', models.TextField()),
                ('active_cases', models.TextField()),
                ('cured', models.TextField()),
                ('death', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('pincode', models.IntegerField(primary_key=True, serialize=False)),
                ('zone', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Self_assess',
            fields=[
                ('phno', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('symptoms', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=100)),
                ('travelled', models.CharField(max_length=3)),
                ('applies', models.CharField(max_length=100)),
                ('result', models.CharField(default='Low', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State_wise',
            fields=[
                ('state', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('state_discharged', models.IntegerField()),
                ('state_case', models.IntegerField()),
                ('state_deaths', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Totalcases',
            fields=[
                ('total_case', models.IntegerField(primary_key=True, serialize=False)),
                ('total_discharged', models.IntegerField()),
                ('total_deaths', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('beds', models.CharField(max_length=4, null=True)),
                ('hosp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('pincodes', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='c.locations', verbose_name='pin')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital_phones',
            fields=[
                ('sl_no', models.IntegerField(primary_key=True, serialize=False)),
                ('phno', models.BigIntegerField()),
                ('h_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='c.hospitals', verbose_name='hid')),
            ],
        ),
    ]
